# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import places.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=places.models.create_path_for_picture)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('indoors_capacity', models.IntegerField(blank=True, null=True, validators=[places.models.Place.validate_more_than_cero])),
                ('outdoors_capacity', models.IntegerField(blank=True, null=True, validators=[places.models.Place.validate_more_than_cero])),
                ('min_capacity', models.IntegerField(blank=True, null=True, validators=[places.models.Place.validate_more_than_cero])),
                ('parking_capacity', models.IntegerField(blank=True, null=True, validators=[places.models.Place.validate_more_than_cero])),
                ('kitchen_sqrt_m', models.IntegerField(blank=True, null=True, validators=[places.models.Place.validate_more_than_cero])),
                ('food', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('heating', models.BooleanField()),
                ('games', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('latitude_longitude', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telephone number has to be exactly 10 digits and contain only numbers, no spaces or hyphen minus', regex='^\\d{10}$')])),
                ('phone_type', models.CharField(choices=[('cell', 'Cellphone'), ('local', 'Localphone')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('address_line_3', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=5)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.Place')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('picture', models.ImageField(upload_to=places.models.create_path_for_picture)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.Place')),
            ],
        ),
        migrations.AddField(
            model_name='telephone',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='representative',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='picture',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='locality',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Region'),
        ),
        migrations.AddField(
            model_name='email',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Locality'),
        ),
    ]
