# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_Correct_functional_dependencies_in_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='locality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
