# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_Alter_Region_and_Locality_for_simplification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='aux_power_generator',
        ),
    ]
