# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_aux_power_generator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='restrooms',
            new_name='food',
        ),
    ]
